# Sentiment Analysis

### Loading dataset

In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv("E:/Dataset/IMDB_Review.csv")

In [3]:
data.sample(4)

                                                  review sentiment
3595   I knew it was going to be awful but not this a...  negative
47368  I was swept into this series just as surely as...  positive
13912  If Bob Ludlum was to see this mini series, he ...  negative
24866  This is not a good movie. It is a tried remake...  negative

In [4]:
data.shape

(50000, 2)

In [5]:
data['review'][0]

"One of the other reviewers has mentioned that after watching just 1 Oz episode you'll be hooked. They are right, as this is exactly what happened with me.<br /><br />The first thing that struck me about Oz was its brutality and unflinching scenes of violence, which set in right from the word GO. Trust me, this is not a show for the faint hearted or timid. This show pulls no punches with regards to drugs, sex or violence. Its is hardcore, in the classic use of the word.<br /><br />It is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary. It focuses mainly on Emerald City, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. Em City is home to many..Aryans, Muslims, gangstas, Latinos, Christians, Italians, Irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.<br /><br />I would say the main appeal of the show is due to the fact that it goes where other shows wouldn't dare. Forget pretty pictures painted for mainstream audiences, forget charm, forget romance...OZ doesn't mess around. The first episode I ever saw struck me as so nasty it was surreal, I couldn't say I was ready for it, but as I watched more, I developed a taste for Oz, and got accustomed to the high levels of graphic violence. Not just violence, but injustice (crooked guards who'll be sold out for a nickel, inmates who'll kill on order and get away with it, well mannered, middle class inmates being turned into prison bitches due to their lack of street skills or prison experience) Watching Oz, you may become comfortable with what is uncomfortable viewing....thats if you can get in touch with your darker side."

### Data Cleaning Process
#### 1. Sample 10000 rows
#### 2. Remove HTML Tags
#### 3. Remove special characters
#### 4. Converting every words into lower case
#### 5. Removing common words
#### 6. Stemming (watching -> watch)

In [9]:
df = data.sample(40000).reset_index(drop=True)

In [10]:
df.head()

                                              review sentiment
0  Sitting in a big wing chair with a huge book i...  negative
1  Thanks to a smart script and a steady hand fro...  positive
2  The "Trivia" page on IMDb claims the filmmaker...  negative
3  This movie is one of the worst remakes I have ...  negative
4  I don't know if this is one of the SyFy Channe...  negative

In [11]:
df.shape

(40000, 2)

#### Understanding the data

In [12]:
df.isnull().value_counts()

review  sentiment
False   False        40000
Name: count, dtype: int64

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40000 entries, 0 to 39999
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   review     40000 non-null  object
 1   sentiment  40000 non-null  object
dtypes: object(2)
memory usage: 625.1+ KB

#### Encode the output column as a number

In [15]:
from sklearn.preprocessing import LabelEncoder

In [16]:
encoder = LabelEncoder()

In [17]:
df['sentiment'] = encoder.fit_transform(df['sentiment'])

In [18]:
df

                                                  review  sentiment
0      Sitting in a big wing chair with a huge book i...          0
1      Thanks to a smart script and a steady hand fro...          1
2      The "Trivia" page on IMDb claims the filmmaker...          0
3      This movie is one of the worst remakes I have ...          0
4      I don't know if this is one of the SyFy Channe...          0
...                                                  ...        ...
39995  I do not fail to recognize Haneke's above-aver...          0
39996  Eh oui, impossible n'est pas gaulois.<br /><br...          1
39997  magellan33 said: "You can only do so much when...          1
39998  I first heard about The Melancholy of Haruhi S...          1
39999  Chaplin stars in a dual role as a jewish barbe...          1

[40000 rows x 2 columns]

#### Remove HTML tags from reviews

In [20]:
import re  # Regular Expression
clean = re.compile("<.*?>")
re.sub(clean, ' ', df.iloc[2].review)

'The "Trivia" page on IMDb claims the filmmakers protested because this film was re-cut by the studio to "simplify the plot". If so, that effort was a total failure, as this is one of the most incoherent narratives I\'ve ever seen in a film -- I\'d hate to have seen it before the plot was "simplified."  It\'s sad to see Warren with so little character to go on that even he can\'t do anything with the inept material. It\'s interesting to see Caron in \'70s mode instead of her Hollywood-era glamour garb and persona, but it\'s sad to see her haplessly wander through this doing-a- favor-to-her-producer-husband dreck. She would actually later hook up with and marry the director, instead -- who, you\'ll note, never directed anything again, but did strictly 1st or 2nd A.D. work in TV from here on out. That oughta tell you enough right there.  I call this "interesting" because I have an automatic fondness for American films of this period, and this role does add perspective to Oates\' otherwise fantastic 1971 output (Two- Lane Blacktop, The Hired Hand). But the "1940s detective as fish-out-of-water in 1970s L.A." theme, which is the only thing the movie really has to say, is sold in way too heavy- handed a manner. A similar theme would be far more effectively handled two years later in Altman\'s The Long Goodbye. And as far as Oates playing a hard-bitten guy on a doomed errand, three years on, he would give his definitive performance in Bring Me the Head of Alfredo Garcia. If you haven\'t seen those, don\'t waste your time with this!'

In [21]:
# Function to clean HTML Tags

def clean_html(text):
    clean = re.compile("<.*?>")
    return re.sub(clean, ' ', text)

In [22]:
df['cleaned_review'] = df['review'].apply(clean_html)

In [23]:
df.sample(2)

,review,sentiment,cleaned_review
28529,And thus was born the most amorous skunk ever ...,1,And thus was born the most amorous skunk ever ...
15737,IF you love movies about fruity dudes who pran...,0,IF you love movies about fruity dudes who pran...

#### Converting all the letters into lower case

In [24]:
# Function to convert to lower case

def convert_lower(text):
    return text.lower()

In [25]:
df['cleaned_review'] = df['cleaned_review'].apply(convert_lower)

#### Removing special characers (₹, #, &) from reviews

In [26]:
# Function to remove special character

def remove_special(text):
    x = ''
    for ch in text:
        if ch.isalnum():
            x = x+ch
        else:
            x = x+' '
            
    return x

In [27]:
df['cleaned_review'] = df['cleaned_review'].apply(remove_special)

#### Removing stopwords (common words)

In [28]:
# Remove stopwords
import nltk  # Natural Language Toolkit

In [29]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to C:\Users\Gautam
[nltk_data]     Kumar\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [31]:
from nltk.corpus import stopwords

In [32]:
len(stopwords.words('english'))  # Total stopwords in english

198

In [33]:
stop_words = set(stopwords.words('english'))

def remove_stopwords(text):
    x = []
    for wrd in text.split():
        if wrd not in stop_words:
            x.append(wrd)

    return x

In [34]:
df['cleaned_review'] = df['cleaned_review'].apply(remove_stopwords)

In [35]:
df.sample(4)

,review,sentiment,cleaned_review
17083,Burt Reynolds' riposte to Clint Eastwood encro...,1,"[burt, reynolds, riposte, clint, eastwood, enc..."
1199,Once upon a time there was a director by the n...,0,"[upon, time, director, name, james, brought, u..."
38663,"WrestleMania 6 took place April 1, 1990 at the...",1,"[wrestlemania, 6, took, place, april, 1, 1990,..."
27099,"Living in the Middle East (in Israel), I was e...",0,"[living, middle, east, israel, excited, bought..."

#### Stemming, or lemmatizing the words

In [36]:
from nltk.stem.porter import PorterStemmer

In [37]:
ps = PorterStemmer()

In [38]:
def stem_words(text):
    x = []
    for wrd in text:
        x.append(ps.stem(wrd))

    return x

In [39]:
df['cleaned_review'] = df['cleaned_review'].apply(stem_words)

In [40]:
df.head()

,review,sentiment,cleaned_review
0,Sitting in a big wing chair with a huge book i...,0,"[sit, big, wing, chair, huge, book, lap, one, ..."
1,Thanks to a smart script and a steady hand fro...,1,"[thank, smart, script, steadi, hand, writer, d..."
2,"The ""Trivia"" page on IMDb claims the filmmaker...",0,"[trivia, page, imdb, claim, filmmak, protest, ..."
3,This movie is one of the worst remakes I have ...,0,"[movi, one, worst, remak, ever, seen, life, ac..."
4,I don't know if this is one of the SyFy Channe...,0,"[know, one, syfi, channel, origin, movi, exact..."

#### Again joining words and create review like string

In [41]:
def join_back(list_input):
    return " ".join(list_input)

In [42]:
df['cleaned_review'] = df['cleaned_review'].apply(join_back)

In [43]:
df.head(3)

,review,sentiment,cleaned_review
0,Sitting in a big wing chair with a huge book i...,0,sit big wing chair huge book lap one bela lugo...
1,Thanks to a smart script and a steady hand fro...,1,thank smart script steadi hand writer director...
2,"The ""Trivia"" page on IMDb claims the filmmaker...",0,trivia page imdb claim filmmak protest film cu...

In [44]:
x = df.iloc[:, 2].values

In [45]:
x[0]

'sit big wing chair huge book lap one bela lugosi look camera dread vocal deliveri sound mock read shakespear inton sloooow ly man constant grope thing unknown draw endless reach time bring light mani startl thing snicker startl seem new lugosi eye bulg rais eyebrow mouth sneer continu new sign age cue visual lighten accompani sound thunder continu rumbl astonish 86 second begin arguabl worst film ever made movi almost defi descript told semi docudrama style unseen narrat explain plot stori revolv around vicissitud man name glen ed wood jr cross dress henc refer glenda film real structur instead consist mostli random assort vignett may may relat glen cross dress motif one long sequenc consist unknown woman wriggl sofa follow man whip woman would today refer odd moment bela reappear appar reason babbl inan dialogu like wrong right right wrong pull string danc huh twenti percent film visual consist stock footag accompani vo relat stori motif visual henc see stock footag bustl citi street freeway traffic thunder herd buffalo playground full kid get wors film cross dress 58 consecut second stock footag foundri furnac make hot steel 84 consecut second battl scene wwii even simplest item botch one scene see newspap headlin read man nab dress girl underneath headlin clearli glu past articl tax one favorit scene screen woman spout airplan creator voic sound like inhal helium except perform lyle talbot act uniformli horrend product design cheap look drab gotta love tacki wallpap edit sloppi background music suitabl 1950 style elev b w cinematographi way much contrast costum look like someth came thrift store film bad make plan 9 outer space look like citizen kane comparison know one could make film wors ed wood glen glenda thank got bela lugosi everi time open mouth gaze camera big bulg eye fell floor laugh'

In [46]:
x.shape

(40000,)

#### Convert reviews from number to a dictionary of words

In [47]:
from sklearn.feature_extraction.text import CountVectorizer

In [48]:
cv = CountVectorizer(max_features=1200)

In [49]:
x_vectorized = cv.fit_transform(x).toarray()

In [50]:
x_vectorized.shape

(40000, 1200)

In [51]:
x_vectorized[0]

array([0, 0, 0, ..., 0, 0, 0], shape=(1200,))

In [52]:
y = df.iloc[:, 1].values

In [53]:
y

array([0, 1, 0, ..., 1, 1, 1], shape=(40000,))

## Starts training the model

In [54]:
from sklearn.model_selection import train_test_split

In [55]:
x_train, x_test, y_train, y_test = train_test_split(x_vectorized, y, test_size=0.2, random_state=18)

In [56]:
from sklearn.naive_bayes import GaussianNB, MultinomialNB, BernoulliNB

In [57]:
gaussian_NB = GaussianNB()
multi_NB = MultinomialNB()
bernoulli_NB = BernoulliNB()

In [58]:
gaussian_NB.fit(x_train, y_train)

GaussianNB()

In [59]:
multi_NB.fit(x_train, y_train)

MultinomialNB()

In [60]:
bernoulli_NB.fit(x_train, y_train)

BernoulliNB()

In [61]:
gaussian_pred = gaussian_NB.predict(x_test)

In [62]:
multi_pred = multi_NB.predict(x_test)

In [63]:
bernoulli_pred = bernoulli_NB.predict(x_test)

#### Testing our model

In [64]:
from sklearn.metrics import accuracy_score, precision_score

In [65]:
print("Accuracy -")
print(f"Gaussian :", accuracy_score(y_test, gaussian_pred))
print(f"Multinomial :", accuracy_score(y_test, multi_pred))
print(f"Bernoulli :", accuracy_score(y_test, bernoulli_pred))

Accuracy -
Gaussian : 0.795875
Multinomial : 0.838625
Bernoulli : 0.840875

In [66]:
print("Precision -")
print(f"Gaussian :", precision_score(y_test, gaussian_pred))
print(f"Multinomial :", precision_score(y_test, multi_pred))
print(f"Bernoulli :", precision_score(y_test, bernoulli_pred))

Precision -
Gaussian : 0.8147632311977716
Multinomial : 0.8270487682252388
Bernoulli : 0.8229783037475346