# Sentiment Analysis

### Loading dataset

In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv("E:/Dataset/IMDB_Review.csv")

In [3]:
data.sample(4)

                                                  review sentiment
7853   A strong woman oriented subject after long, di...  positive
38692  If you go to the cinema to be entertained, amu...  positive
5249   When I heard that Adrian Pasdar was in drag in...  positive
18896  Four prisoners share a single cell: the domine...  positive

In [4]:
data.shape

(50000, 2)

In [5]:
data['review'][0]

"One of the other reviewers has mentioned that after watching just 1 Oz episode you'll be hooked. They are right, as this is exactly what happened with me.<br /><br />The first thing that struck me about Oz was its brutality and unflinching scenes of violence, which set in right from the word GO. Trust me, this is not a show for the faint hearted or timid. This show pulls no punches with regards to drugs, sex or violence. Its is hardcore, in the classic use of the word.<br /><br />It is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary. It focuses mainly on Emerald City, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. Em City is home to many..Aryans, Muslims, gangstas, Latinos, Christians, Italians, Irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.<br /><br />I would say the main appeal of the show is due to the fact that it goes where other shows wouldn't dare. Forget pretty pictures painted for mainstream audiences, forget charm, forget romance...OZ doesn't mess around. The first episode I ever saw struck me as so nasty it was surreal, I couldn't say I was ready for it, but as I watched more, I developed a taste for Oz, and got accustomed to the high levels of graphic violence. Not just violence, but injustice (crooked guards who'll be sold out for a nickel, inmates who'll kill on order and get away with it, well mannered, middle class inmates being turned into prison bitches due to their lack of street skills or prison experience) Watching Oz, you may become comfortable with what is uncomfortable viewing....thats if you can get in touch with your darker side."

### Data Cleaning Process
#### 1. Sample 10000 rows
#### 2. Remove HTML Tags
#### 3. Remove special characters
#### 4. Converting every words into lower case
#### 5. Removing common words
#### 6. Stemming (watching -> watch)

In [6]:
df = data.sample(10000).reset_index(drop=True)

In [7]:
df.head()

                                              review sentiment
0  Effort aside (This isn't a review about good i...  negative
1  normally,i would say i loved this movie.not fo...  negative
2  Maybe we Aussies just have a totally different...  negative
3  I was expecting a lot more of this film than w...  negative
4  I love these awful 80's summer camp movies. Th...  negative

In [8]:
df.shape

(10000, 2)

In [9]:
df.isnull().value_counts()

review  sentiment
False   False        10000
Name: count, dtype: int64

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   review     10000 non-null  object
 1   sentiment  10000 non-null  object
dtypes: object(2)
memory usage: 156.4+ KB

In [11]:
df['sentiment'].replace({'positive': 1, 'negative': 0}, inplace=True)

C:\Users\Gautam Kumar\AppData\Local\Temp\ipykernel_20064\3188136084.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['sentiment'].replace({'positive': 1, 'negative': 0}, inplace=True)
C:\Users\Gautam Kumar\AppData\Local\Temp\ipykernel_20064\3188136084.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['sentiment'].replace({'positive': 1, 'negative': 0}, inplace=True)

In [12]:
df.sample(2)

                                                 review  sentiment
5948  I saw the omen when i was 11 on tv. I enjoyed ...          0
9899  Before seeing this film, I suggest the viewer ...          1

In [13]:
import re
clean = re.compile("<.*?>")
re.sub(clean, ' ', df.iloc[2].review)

'Maybe we Aussies just have a totally different sense of humour and therein my lie the only problem here. I have a database of all the DVDs I own (including those received as gifts - which this was) and so, when entering a new one, I always refer to IMDb for such info as genre, runtime, director, leads etc. When entering this, I noted that it was a comedy and so I decided to watch it at a time when I wanted something light and a good laugh. Well, it was neither! There were absolutely NO laughs at all and an inordinate amount of gratuitous profanity (are there REALLY radio announcers allowed to broadcast the sort of filth that Steve Jones dishes out? What if a decent child happened to tune to his station?).  Rather than enjoy a good laugh (or even a little giggle) I found the whole thing thoroughly depressing. I have given it 3 out of 10 but, to be honest, I don\'t know what those 3 are for! I suppose the basics of lighting and sound weren\'t too bad!   We have an ostensibly stone-broke loser (Giovanni Ribisi) who still seems to be able to drive a reasonable car (who pays for the fuel?) and live in what could be a nice apartment (who pays his rent?) Given the opportunity of forming what might have been some sort of meaningful relationship with what turned out to be a nice girl, he even blew that! Perhaps it was she (Lynn Collins) who earned this movie the 3 points! The fact that she works as a stripper rather than a hairdresser is one of the few aspects of this movie that makes sense ("I make as much in one night doing this as I do in two weeks\' hairdressing").  Unless you want to get depressed and bored to the teeth, forget it!'

In [14]:
# Function to clean HTML Tags

def clean_html(text):
    clean = re.compile("<.*?>")
    return re.sub(clean, ' ', text)

In [15]:
df['cleaned_review'] = df['review'].apply(clean_html)

In [16]:
df.sample()

,review,sentiment,cleaned_review
3005,Some teen agers go to an old deserted farm hou...,0,Some teen agers go to an old deserted farm hou...

In [17]:
# Function to convert to lower case

def convert_lower(text):
    return text.lower()

In [18]:
df['cleaned_review'] = df['cleaned_review'].apply(convert_lower)

In [19]:
# Function to remove special character

def remove_special(text):
    x = ''
    for ch in text:
        if ch.isalnum():
            x = x+ch
        else:
            x = x+' '
            
    return x

In [20]:
df['cleaned_review'] = df['cleaned_review'].apply(remove_special)

In [21]:
# Remove stopwords
import nltk  # Natural Language Toolkit

In [22]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to C:\Users\Gautam
[nltk_data]     Kumar\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [23]:
from nltk.corpus import stopwords

In [24]:
len(stopwords.words('english'))  # Total stopwords in english

198

In [25]:
stop_words = set(stopwords.words('english'))

def remove_stopwords(text):
    x = []
    for wrd in text.split():
        if wrd not in stop_words:
            x.append(wrd)

    return x

In [26]:
df['cleaned_review'] = df['cleaned_review'].apply(remove_stopwords)

In [27]:
df

,review,sentiment,cleaned_review
0,Effort aside (This isn't a review about good i...,0,"[effort, aside, review, good, intentions, fina..."
1,"normally,i would say i loved this movie.not fo...",0,"[normally, would, say, loved, movie, acting, a..."
2,Maybe we Aussies just have a totally different...,0,"[maybe, aussies, totally, different, sense, hu..."
3,I was expecting a lot more of this film than w...,0,"[expecting, lot, film, actually, got, acting, ..."
4,I love these awful 80's summer camp movies. Th...,0,"[love, awful, 80, summer, camp, movies, best, ..."
...,...,...,...
9995,This has to be the worst piece of garbage I've...,0,"[worst, piece, garbage, seen, heath, ledger, h..."
9996,I am a big fan of low budget horror movies lik...,0,"[big, fan, low, budget, horror, movies, like, ..."
9997,... but you probably have seen it or else you ...,1,"[probably, seen, else, obscure, probably, stum..."
9998,"If you enjoy sitting in the dark, both literal...",0,"[enjoy, sitting, dark, literally, figuratively..."
9999,"In my opinion, this is the best stand-up show ...",1,"[opinion, best, stand, show, ever, seen, becam..."

In [28]:
from nltk.stem.porter import PorterStemmer

In [29]:
ps = PorterStemmer()

In [30]:
def stem_words(text):
    x = []
    for wrd in text:
        x.append(ps.stem(wrd))

    return x

In [31]:
df['cleaned_review'] = df['cleaned_review'].apply(stem_words)

In [32]:
df

,review,sentiment,cleaned_review
0,Effort aside (This isn't a review about good i...,0,"[effort, asid, review, good, intent, final, pr..."
1,"normally,i would say i loved this movie.not fo...",0,"[normal, would, say, love, movi, act, although..."
2,Maybe we Aussies just have a totally different...,0,"[mayb, aussi, total, differ, sens, humour, the..."
3,I was expecting a lot more of this film than w...,0,"[expect, lot, film, actual, got, act, aw, ever..."
4,I love these awful 80's summer camp movies. Th...,0,"[love, aw, 80, summer, camp, movi, best, part,..."
...,...,...,...
9995,This has to be the worst piece of garbage I've...,0,"[worst, piec, garbag, seen, heath, ledger, hea..."
9996,I am a big fan of low budget horror movies lik...,0,"[big, fan, low, budget, horror, movi, like, co..."
9997,... but you probably have seen it or else you ...,1,"[probabl, seen, els, obscur, probabl, stumbl, ..."
9998,"If you enjoy sitting in the dark, both literal...",0,"[enjoy, sit, dark, liter, figur, nineti, minut..."
9999,"In my opinion, this is the best stand-up show ...",1,"[opinion, best, stand, show, ever, seen, becam..."

In [33]:
# Join back

def join_back(list_input):
    return "".join(list_input)

In [34]:
df['cleaned_review'] = df['cleaned_review'].apply(join_back)

In [35]:
df['cleaned_review']

0       effortasidreviewgoodintentfinalproductfilmpoor...
1       normalwouldsaylovemoviactalthoughokscriptreaso...
2       maybaussitotaldiffersenshumourthereinlieproble...
3       expectlotfilmactualgotactaweveryonstorifarimpr...
4       loveaw80summercampmovibestpartparticampfactlit...
                              ...
9995    worstpiecgarbagseenheathledgerheartthroblookde...
9996    bigfanlowbudgethorrormovilikecomeworstpiecmonk...
9997    probablseenelsobscurprobablstumblontolikelittl...
9998    enjoysitdarkliterfigurninetiminutmoviwastactor...
9999    opinionbeststandshoweverseenbecaminstanteddifa...
Name: cleaned_review, Length: 10000, dtype: object

In [36]:
x = df.iloc[:, 2].values

In [37]:
x.shape

(10000,)

In [38]:
from sklearn.feature_extraction.text import CountVectorizer

In [39]:
cv = CountVectorizer()

In [40]:
x_vectorized = cv.fit_transform(x).toarray()

In [41]:
x_vectorized.shape

(10000, 9982)

In [42]:
x_vectorized[0]

array([0, 0, 0, ..., 0, 0, 0], shape=(9982,))

In [43]:
y = df.iloc[:, 1].values

In [44]:
y

array([0, 0, 0, ..., 1, 0, 1], shape=(10000,))

In [45]:
y.shape

(10000,)