# Encoding Categorical data

## a) Ordinal Encoding (For input cols), Label encoding (For output col)

In [56]:
import numpy as np
import pandas as pd

### Loading dataset

In [28]:
df = pd.read_csv('E:/Dataset/customer.csv')

In [29]:
df.sample(5)

    age  gender   review education purchased
33   89  Female     Good        PG       Yes
14   15    Male     Poor        PG       Yes
46   64  Female     Poor        PG        No
30   73    Male  Average        UG        No
12   51    Male     Poor    School        No

In [30]:
df = df.iloc[:,2:]

In [31]:
df.head()

    review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

### Working on ordinal categorical column

#### Input columns (Ordinal encoding)

In [32]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(df.iloc[:,0:2], df.iloc[:, -1], test_size=0.2, random_state=2)

In [33]:
x_train.shape, x_test.shape

((40, 2), (10, 2))

In [34]:
from sklearn.preprocessing import OrdinalEncoder

In [35]:
oe = OrdinalEncoder(categories=[['Poor','Average','Good'], ['School','UG','PG']])

In [36]:
oe.fit(x_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [37]:
x_train_scaled = oe.transform(x_train)
x_test_scaled = oe.transform(x_test)

In [40]:
x_train_scaled

array([[1., 2.],
       [2., 1.],
       [0., 1.],
       [0., 0.],
       [0., 2.],
       [2., 2.],
       [0., 1.],
       [2., 2.],
       [2., 0.],
       [0., 2.],
       [1., 1.],
       [1., 0.],
       [1., 1.],
       [0., 1.],
       [1., 1.],
       [0., 0.],
       [2., 2.],
       [0., 2.],
       [1., 2.],
       [2., 1.],
       [1., 1.],
       [2., 0.],
       [2., 2.],
       [1., 0.],
       [0., 2.],
       [2., 0.],
       [1., 2.],
       [2., 2.],
       [0., 0.],
       [1., 0.],
       [0., 0.],
       [2., 1.],
       [2., 1.],
       [2., 0.],
       [0., 2.],
       [0., 2.],
       [1., 1.],
       [0., 2.],
       [0., 1.],
       [2., 0.]])

In [47]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

#### Output column (Label encoding)

In [41]:
from sklearn.preprocessing import LabelEncoder

In [42]:
le = LabelEncoder()

In [52]:
le.fit(y_train)

LabelEncoder()

In [53]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [54]:
y_train_scaled = le.transform(y_train)
y_test_scaled = le.transform(y_test)

In [55]:
y_train_scaled

array([1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0])

## b) One Hot Encoding (For nominal data)

### Loading dataset

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('E:/Dataset/cars.csv')

In [3]:
df

        brand  km_driven    fuel                 owner  selling_price
0      Maruti     145500  Diesel           First Owner         450000
1       Skoda     120000  Diesel          Second Owner         370000
2       Honda     140000  Petrol           Third Owner         158000
3     Hyundai     127000  Diesel           First Owner         225000
4      Maruti     120000  Petrol           First Owner         130000
...       ...        ...     ...                   ...            ...
8123  Hyundai     110000  Petrol           First Owner         320000
8124  Hyundai     119000  Diesel  Fourth & Above Owner         135000
8125   Maruti     120000  Diesel           First Owner         382000
8126     Tata      25000  Diesel           First Owner         290000
8127     Tata      25000  Diesel           First Owner         290000

[8128 rows x 5 columns]

In [4]:
df.nunique()

brand             32
km_driven        921
fuel               4
owner              5
selling_price    677
dtype: int64

In [5]:
df['owner'].value_counts()

owner
First Owner             5289
Second Owner            2105
Third Owner              555
Fourth & Above Owner     174
Test Drive Car             5
Name: count, dtype: int64

In [6]:
df['fuel'].value_counts()

fuel
Diesel    4402
Petrol    3631
CNG         57
LPG         38
Name: count, dtype: int64

### Encoding starts

#### One Hot Encoding using Pandas

In [7]:
pd.get_dummies(df, columns=['fuel','owner'])

,brand,km_driven,selling_price,fuel_CNG,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_First Owner,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,False,True,False,False,True,False,False,False,False
1,Skoda,120000,370000,False,True,False,False,False,False,True,False,False
2,Honda,140000,158000,False,False,False,True,False,False,False,False,True
3,Hyundai,127000,225000,False,True,False,False,True,False,False,False,False
4,Maruti,120000,130000,False,False,False,True,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,False,True,True,False,False,False,False
8124,Hyundai,119000,135000,False,True,False,False,False,True,False,False,False
8125,Maruti,120000,382000,False,True,False,False,True,False,False,False,False
8126,Tata,25000,290000,False,True,False,False,True,False,False,False,False
8127,Tata,25000,290000,False,True,False,False,True,False,False,False,False

#### K-1 One Hot Encoding using pandas

In [8]:
pd.get_dummies(df, columns=['fuel','owner'], drop_first=True)

,brand,km_driven,selling_price,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,True,False,False,False,False,False,False
1,Skoda,120000,370000,True,False,False,False,True,False,False
2,Honda,140000,158000,False,False,True,False,False,False,True
3,Hyundai,127000,225000,True,False,False,False,False,False,False
4,Maruti,120000,130000,False,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,True,False,False,False,False
8124,Hyundai,119000,135000,True,False,False,True,False,False,False
8125,Maruti,120000,382000,True,False,False,False,False,False,False
8126,Tata,25000,290000,True,False,False,False,False,False,False
8127,Tata,25000,290000,True,False,False,False,False,False,False

#### One Hot Encoding using Scikit-Learn

In [9]:
df.head()

     brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [11]:
from sklearn.model_selection import train_test_split
x_train,x_test, y_train, y_test = train_test_split(df.iloc[:,:4], df.iloc[:,-1], test_size=0.3, random_state=1)

In [17]:
print(x_train.head()), x_train.shape, x_test.shape

          brand  km_driven    fuel         owner
2246  Chevrolet      50000  Petrol   First Owner
2095  Chevrolet     120000  Diesel  Second Owner
3290    Hyundai      60000  Petrol   First Owner
6868     Maruti       5000  Petrol   First Owner
6895   Mahindra      40000  Diesel   First Owner

(None, (5689, 4), (2439, 4))

In [18]:
from sklearn.preprocessing import OneHotEncoder

In [53]:
ohe = OneHotEncoder()
ohe2 = OneHotEncoder(drop='first', sparse_output=False, dtype=np.int32)

##### - By use of drop parameter, you can drop the first column so that it can remove multicolinearity
##### - It return a sparse array(majority of elements is zero), so to remove this we use sparse_output
##### - It return data_type as float64, but you can control using dtype parameter

In [54]:
x_train_new = ohe.fit_transform(df[['fuel','owner']]).toarray()

In [55]:
x_test_new = ohe.transform(df[['fuel','owner']]).toarray()

In [56]:
x_train_new # A numpy array

array([[0., 1., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.],
       ...,
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.]], shape=(8128, 9))

In [57]:
new_x_train = np.hstack((df[['brand','km_driven']].values,x_train_new))
new_x_train

array([['Maruti', 145500, 0.0, ..., 0.0, 0.0, 0.0],
       ['Skoda', 120000, 0.0, ..., 1.0, 0.0, 0.0],
       ['Honda', 140000, 0.0, ..., 0.0, 0.0, 1.0],
       ...,
       ['Maruti', 120000, 0.0, ..., 0.0, 0.0, 0.0],
       ['Tata', 25000, 0.0, ..., 0.0, 0.0, 0.0],
       ['Tata', 25000, 0.0, ..., 0.0, 0.0, 0.0]],
      shape=(8128, 11), dtype=object)

In [58]:
x_train_encoded = pd.DataFrame(new_x_train)

In [59]:
x_train_encoded

           0       1    2    3    4    5    6    7    8    9    10
0      Maruti  145500  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0
1       Skoda  120000  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0
2       Honda  140000  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0
3     Hyundai  127000  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0
4      Maruti  120000  0.0  0.0  0.0  1.0  1.0  0.0  0.0  0.0  0.0
...       ...     ...  ...  ...  ...  ...  ...  ...  ...  ...  ...
8123  Hyundai  110000  0.0  0.0  0.0  1.0  1.0  0.0  0.0  0.0  0.0
8124  Hyundai  119000  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0
8125   Maruti  120000  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0
8126     Tata   25000  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0
8127     Tata   25000  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0

[8128 rows x 11 columns]

#### OneHotEncoding with top categories

In [66]:
counts = df['brand'].value_counts()
counts

brand
Maruti           2448
Hyundai          1415
Mahindra          772
Tata              734
Toyota            488
Honda             467
Ford              397
Chevrolet         230
Renault           228
Volkswagen        186
BMW               120
Skoda             105
Nissan             81
Jaguar             71
Volvo              67
Datsun             65
Mercedes-Benz      54
Fiat               47
Audi               40
Lexus              34
Jeep               31
Mitsubishi         14
Force               6
Land                6
Isuzu               5
Kia                 4
Ambassador          4
Daewoo              3
MG                  3
Ashok               1
Opel                1
Peugeot             1
Name: count, dtype: int64

In [76]:
repl = counts[counts <= 100].index  # Brands which have less than 100 cars

In [78]:
pd.get_dummies(df['brand'].replace(repl, "uncommon"))

,BMW,Chevrolet,Ford,Honda,Hyundai,Mahindra,Maruti,Renault,Skoda,Tata,Toyota,Volkswagen,uncommon
0,False,False,False,False,False,False,True,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,True,False,False,False,False
2,False,False,False,True,False,False,False,False,False,False,False,False,False
3,False,False,False,False,True,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,True,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8123,False,False,False,False,True,False,False,False,False,False,False,False,False
8124,False,False,False,False,True,False,False,False,False,False,False,False,False
8125,False,False,False,False,False,False,True,False,False,False,False,False,False
8126,False,False,False,False,False,False,False,False,False,True,False,False,False
8127,False,False,False,False,False,False,False,False,False,True,False,False,False