# Handling-Date-Time

### Loading the dataset

In [1]:
import numpy as np
import pandas as pd

In [74]:
date = pd.read_csv('E:/Dataset/orders.csv')
time = pd.read_csv('E:/Dataset/messages.csv')

In [4]:
date.head(3)

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1

In [75]:
time.head(3)

                  date                                               msg
0  2013-12-15 00:50:00                          ищу на сегодня мужика 37
1  2014-04-29 23:40:00  ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00          Днепр.м 43 позн.с д/ж *.о  067.16.34.576

In [6]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   object
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

In [65]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

### Working with Date

In [8]:
date['date'] = pd.to_datetime(date['date'])

In [10]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

#### Extract year

In [11]:
date['date_year'] = date['date'].dt.year

#### Extract month

In [13]:
date['date_month_no'] = date['date'].dt.month

In [14]:
date['date_month_name'] = date['date'].dt.month_name()

#### Extract day

In [16]:
date['date_day'] = date['date'].dt.day

In [18]:
date['date_dow'] = date['date'].dt.dayofweek

In [20]:
date['date_dow_name'] = date['date'].dt.day_name()

In [25]:
date['date_is_weekend'] = np.where(date['date_dow_name'].isin(['Sunday', 'Monday']), 1, 0)

In [26]:
date.sample(2)

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name,date_day,date_dow,date_dow_name,date_is_weekend
551,2019-06-27,6756,17,2,2019,6,June,27,3,Thursday,0
225,2019-04-26,1503,21,12,2019,4,April,26,4,Friday,0

#### Extract week of the year

In [32]:
date['date_week'] = date['date'].dt.isocalendar().week

#### Extract quarter of the year

In [28]:
date['date_quarter'] = date['date'].dt.quarter

#### Extract time elapsed between two dates

In [33]:
import datetime
today = datetime.datetime.today()
today

datetime.datetime(2026, 4, 27, 0, 19, 57, 124211)

In [34]:
today - date['date']

0     2330 days 00:19:57.124211
1     2812 days 00:19:57.124211
2     2743 days 00:19:57.124211
3     2445 days 00:19:57.124211
4     2668 days 00:19:57.124211
                 ...
995   2758 days 00:19:57.124211
996   2699 days 00:19:57.124211
997   2547 days 00:19:57.124211
998   2612 days 00:19:57.124211
999   2386 days 00:19:57.124211
Name: date, Length: 1000, dtype: timedelta64[ns]

In [38]:
(today-date['date']).dt.days

0      2330
1      2812
2      2743
3      2445
4      2668
       ...
995    2758
996    2699
997    2547
998    2612
999    2386
Name: date, Length: 1000, dtype: int64

In [46]:
# Passed week are
np.round((today-date['date'])/np.timedelta64(1,'W'),0)

0      333.0
1      402.0
2      392.0
3      349.0
4      381.0
       ...
995    394.0
996    386.0
997    364.0
998    373.0
999    341.0
Name: date, Length: 1000, dtype: float64

### Working with time

In [76]:
time.sample(2)

                    date                                                msg
677  2013-05-21 00:27:00  красивая дама скучает одна в квартире!Кто на ч...
192  2012-07-11 00:15:00  М 29 ЛЕТ ИЩЕТ ДЕВУШКУ ДЛЯ РЕАЛЬНЫХ И ПРИЯТНЫХ ...

In [77]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

In [79]:
time['date'] = pd.to_datetime(time['date'])

In [81]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[ns]
 1   msg     1000 non-null   object
dtypes: datetime64[ns](1), object(1)
memory usage: 15.8+ KB

#### Extract hour, minute, and second

In [83]:
time['hour'] = time['date'].dt.hour
time['minute'] = time['date'].dt.minute
time['second'] = time['date'].dt.second

In [85]:
time.sample(2)

,date,msg,hour,minute,second
312,2012-01-19 23:41:00,М 40. Познк. с жен. из Днепро-вска с/о. 063-7...,23,41,0
644,2012-03-11 01:23:00,ПАРЕНЬ ПОЗНАКОМИТЬСЯ С ДЕВУШКОЙ. МНЕ 21.809978...,1,23,0

#### Extract time, and date

In [87]:
time['time_time'] = time['date'].dt.time

In [88]:
time['time_date'] = time['date'].dt.date

In [93]:
time.sample()

,date,msg,hour,minute,second,time_time,time_date
944,2015-05-21 23:11:00,П 27/184/90 ищу дев 18-30 лет для с/с совм про...,23,11,0,23:11:00,2015-05-21

#### Finding time difference

In [94]:
today-time['date']

0     4515 days 23:29:57.124211
1     4380 days 00:39:57.124211
2     4865 days 23:58:57.124211
3     4167 days 23:48:57.124211
4     4565 days 01:08:57.124211
                 ...
995   5154 days 23:29:57.124211
996   4476 days 01:05:57.124211
997   4941 days 00:42:57.124211
998   5057 days 00:45:57.124211
999   4329 days 00:54:57.124211
Name: date, Length: 1000, dtype: timedelta64[ns]

In [95]:
(today-time['date'])/np.timedelta64(1,'h')

0      108383.499201
1      105120.665868
2      116783.982535
3      100031.815868
4      109561.149201
           ...
995    123719.499201
996    107425.099201
997    118584.715868
998    121368.765868
999    103896.915868
Name: date, Length: 1000, dtype: float64