# Iterative imputer or MICE(Multivariate Imputation by Chained Equations)

In [1]:
import numpy as np
import pandas as pd

from sklearn.linear_model import LinearRegression

### Doing data ready to understand this concept

In [2]:
df = np.round(pd.read_csv('E:/Dataset/50_startups.csv')/10000)

In [3]:
np.random.seed(4)
df = df.sample(5).copy()
df

    R&D Spend  Administration  Marketing Spend  Profit
32        6.0            10.0             21.0    10.0
45        0.0            12.0             30.0     5.0
4        14.0             9.0             37.0    17.0
15       11.0            12.0             26.0    13.0
38        4.0             8.0             17.0     8.0

In [4]:
df = df.iloc[:,:-1].copy()
df

    R&D Spend  Administration  Marketing Spend
32        6.0            10.0             21.0
45        0.0            12.0             30.0
4        14.0             9.0             37.0
15       11.0            12.0             26.0
38        4.0             8.0             17.0

In [5]:
df.iloc[1,0] = np.nan
df.iloc[3,1] = np.nan
df.iloc[4,2] = np.nan

In [6]:
df

    R&D Spend  Administration  Marketing Spend
32        6.0            10.0             21.0
45        NaN            12.0             30.0
4        14.0             9.0             37.0
15       11.0             NaN             26.0
38        4.0             8.0              NaN

## Iteration - 1

### Step 1 - Impute all missing values with mean of respective column

In [7]:
df0 = pd.DataFrame()

df0['R&D Spend'] = df['R&D Spend'].fillna(df['R&D Spend'].mean())
df0['Administration'] = df['Administration'].fillna(df['Administration'].mean())
df0['Marketing Spend'] = df['Marketing Spend'].fillna(df['Marketing Spend'].mean())

In [8]:
# 0th Iteration
df0

    R&D Spend  Administration  Marketing Spend
32       6.00           10.00             21.0
45       8.75           12.00             30.0
4       14.00            9.00             37.0
15      11.00            9.75             26.0
38       4.00            8.00             28.5

## Iteration - 2

### Step 2 - Making each columns' NaN value again as NaN one by one

In [9]:
df1 = df0.copy()

df1.iloc[1,0] = np.nan

df1

    R&D Spend  Administration  Marketing Spend
32        6.0           10.00             21.0
45        NaN           12.00             30.0
4        14.0            9.00             37.0
15       11.0            9.75             26.0
38        4.0            8.00             28.5

In [10]:
# Use rows which have not missing value as input

x = df1.iloc[[0,2,3,4],1:3]
x

    Administration  Marketing Spend
32           10.00             21.0
4             9.00             37.0
15            9.75             26.0
38            8.00             28.5

In [11]:
y = df1.iloc[[0,2,3,4],0]
y

32     6.0
4     14.0
15    11.0
38     4.0
Name: R&D Spend, dtype: float64

In [12]:
lr = LinearRegression()
lr.fit(x,y)
lr.predict(df1.iloc[1,1:].values.reshape(1,2))

E:\Anaconda\Anaconda2\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([22.16489859])

In [13]:
df1.iloc[1,0] = 22.16

In [14]:
df1

    R&D Spend  Administration  Marketing Spend
32       6.00           10.00             21.0
45      22.16           12.00             30.0
4       14.00            9.00             37.0
15      11.00            9.75             26.0
38       4.00            8.00             28.5

In [15]:
df1.iloc[3,1] = np.nan
df1

    R&D Spend  Administration  Marketing Spend
32       6.00            10.0             21.0
45      22.16            12.0             30.0
4       14.00             9.0             37.0
15      11.00             NaN             26.0
38       4.00             8.0             28.5

In [16]:
x = df1.iloc[[0,1,2,4],[0,2]]
x

    R&D Spend  Marketing Spend
32       6.00             21.0
45      22.16             30.0
4       14.00             37.0
38       4.00             28.5

In [17]:
y = df1.iloc[[0,1,2,4],1]
y

32    10.0
45    12.0
4      9.0
38     8.0
Name: Administration, dtype: float64

In [18]:
lr = LinearRegression()
lr.fit(x,y)
lr.predict(df1.iloc[3,[0,2]].values.reshape(1,2))

E:\Anaconda\Anaconda2\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([10.18234324])

In [19]:
df1.iloc[3,1] = 10.18
df1

    R&D Spend  Administration  Marketing Spend
32       6.00           10.00             21.0
45      22.16           12.00             30.0
4       14.00            9.00             37.0
15      11.00           10.18             26.0
38       4.00            8.00             28.5

In [22]:
df1.iloc[4,2] = np.nan
df1

    R&D Spend  Administration  Marketing Spend
32       6.00           10.00             21.0
45      22.16           12.00             30.0
4       14.00            9.00             37.0
15      11.00           10.18             26.0
38       4.00            8.00              NaN

In [24]:
x = df1.iloc[:4,:-1]
x

    R&D Spend  Administration
32       6.00           10.00
45      22.16           12.00
4       14.00            9.00
15      11.00           10.18

In [25]:
y = df1.iloc[:4,-1]
y

32    21.0
45    30.0
4     37.0
15    26.0
Name: Marketing Spend, dtype: float64

In [38]:
lr = LinearRegression()
lr.fit(x,y)
lr.predict(df1.iloc[4,:-1].values.reshape(1,2))

E:\Anaconda\Anaconda2\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([29.94200728])

In [40]:
df1.iloc[4,-1] = 29.94

In [41]:
# After 1st iteration
df1

    R&D Spend  Administration  Marketing Spend
32       6.00           10.00            21.00
45      22.16           12.00            30.00
4       14.00            9.00            37.00
15      11.00           10.18            26.00
38       4.00            8.00            29.94

### Strp 3 - Sutracting df0 with df0

In [42]:
df1 - df0

    R&D Spend  Administration  Marketing Spend
32       0.00            0.00             0.00
45      13.41            0.00             0.00
4        0.00            0.00             0.00
15       0.00            0.43             0.00
38       0.00            0.00             1.44

## Iteration - 3

#### - Now Repeat the above steps 2, and 3 till subtraction of two consecutive iteration df is zero or tend to zero

In [44]:
df2 = df1.copy()
df2.iloc[1,0] = np.nan
df2

    R&D Spend  Administration  Marketing Spend
32        6.0           10.00            21.00
45        NaN           12.00            30.00
4        14.0            9.00            37.00
15       11.0           10.18            26.00
38        4.0            8.00            29.94

In [47]:
x = df2.iloc[[0,2,3,4], 1:]
y = df2.iloc[[0,2,3,4], 0]
lr = LinearRegression()
lr.fit(x, y)
lr.predict(df2.iloc[1,1:].values.reshape(1,2))

E:\Anaconda\Anaconda2\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([22.34030216])

In [48]:
df2.iloc[1,0] = 22.34

In [51]:
df2.iloc[3,1] = np.nan
x = df2.iloc[[0,1,2,4], [0,2]]
y = df2.iloc[[0,1,2,4], 1]

lr = LinearRegression()
lr.fit(x,y)
lr.predict(df2.iloc[3, [0,2]].values.reshape(1,2))

E:\Anaconda\Anaconda2\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([10.22111001])

In [52]:
df2.iloc[3,1] = 10.22

In [56]:
df2.iloc[4,-1] = np.nan
x = df2.iloc[:-1, :-1]
y = df2.iloc[:-1, -1]

lr = LinearRegression()
lr.fit(x,y)
lr.predict(df2.iloc[4,:-1].values.reshape(1,2))

E:\Anaconda\Anaconda2\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([30.16399321])

In [57]:
df2.iloc[-1,-1] = 30.16

In [59]:
df2

    R&D Spend  Administration  Marketing Spend
32       6.00           10.00            21.00
45      22.34           12.00            30.00
4       14.00            9.00            37.00
15      11.00           10.22            26.00
38       4.00            8.00            30.16

In [58]:
df2 - df1

    R&D Spend  Administration  Marketing Spend
32       0.00            0.00             0.00
45       0.18            0.00             0.00
4        0.00            0.00             0.00
15       0.00            0.04             0.00
38       0.00            0.00             0.22

## Iteration - 4

In [69]:
df3 = df2.copy()

df3.iloc[1,0] = np.nan
x = df3.iloc[[0,2,3,4], 1:]
y = df3.iloc[[0,2,3,4], 0]
lr = LinearRegression()
lr.fit(x, y)
pred = lr.predict(df3.iloc[1,1:].values.reshape(1,2))
df3.iloc[1,0] = np.round(pred,2)

df3.iloc[3,1] = np.nan
x = df3.iloc[[0,1,2,4], [0,2]]
y = df3.iloc[[0,1,2,4], 1]
lr = LinearRegression()
lr.fit(x,y)
pred = lr.predict(df3.iloc[3, [0,2]].values.reshape(1,2))
df3.iloc[3,1] = np.round(pred,2)

df3.iloc[4,-1] = np.nan
x = df3.iloc[:-1, :-1]
y = df3.iloc[:-1, -1]
lr = LinearRegression()
lr.fit(x,y)
pred = lr.predict(df3.iloc[4,:-1].values.reshape(1,2))
df3.iloc[4,-1] = np.round(pred,2)

E:\Anaconda\Anaconda2\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
E:\Anaconda\Anaconda2\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
E:\Anaconda\Anaconda2\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

In [70]:
df3

    R&D Spend  Administration  Marketing Spend
32       6.00           10.00            21.00
45      22.37           12.00            30.00
4       14.00            9.00            37.00
15      11.00           10.23            26.00
38       4.00            8.00            30.21

In [71]:
df3 - df2

    R&D Spend  Administration  Marketing Spend
32       0.00            0.00             0.00
45       0.03            0.00             0.00
4        0.00            0.00             0.00
15       0.00            0.01             0.00
38       0.00            0.00             0.05