# Iterative imputer or MICE(Multivariate Imputation by Chained Equations)

In [1]:
import numpy as np
import pandas as pd

### Doing data ready to understand this concept

In [105]:
df = np.round(pd.read_csv('E:/Dataset/50_startups.csv')/10000)

In [106]:
np.random.seed(4)
df = df.sample(5).copy()
df

    R&D Spend  Administration  Marketing Spend  Profit
32        6.0            10.0             21.0    10.0
45        0.0            12.0             30.0     5.0
4        14.0             9.0             37.0    17.0
15       11.0            12.0             26.0    13.0
38        4.0             8.0             17.0     8.0

In [107]:
df = df.iloc[:,:-1].copy()
df

    R&D Spend  Administration  Marketing Spend
32        6.0            10.0             21.0
45        0.0            12.0             30.0
4        14.0             9.0             37.0
15       11.0            12.0             26.0
38        4.0             8.0             17.0

In [108]:
df.iloc[1,0] = np.nan
df.iloc[3,1] = np.nan
df.iloc[4,2] = np.nan

In [109]:
df

    R&D Spend  Administration  Marketing Spend
32        6.0            10.0             21.0
45        NaN            12.0             30.0
4        14.0             9.0             37.0
15       11.0             NaN             26.0
38        4.0             8.0              NaN

### Step 1 - Impute all missing values with mean of respective col

In [110]:
df0 = pd.DataFrame()

df0['R&D Spend'] = df['R&D Spend'].fillna(df['R&D Spend'].mean())
df0['Administration'] = df['Administration'].fillna(df['Administration'].mean())
df0['Marketing Spend'] = df['Marketing Spend'].fillna(df['Marketing Spend'].mean())

In [111]:
# 0th Iteration
df0

    R&D Spend  Administration  Marketing Spend
32       6.00           10.00             21.0
45       8.75           12.00             30.0
4       14.00            9.00             37.0
15      11.00            9.75             26.0
38       4.00            8.00             28.5

### Step 2 - Making each columns' NaN value again as NaN